# Generated by Django 4.1.7 on 2023-03-25 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitzforecast', '0002_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gross_sales',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.CreateModel(
            name='GrossSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('gross_sales', models.FloatField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitzforecast.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitzforecast.product')),
            ],
        ),
    ]
